import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

// Market Pulse ingestion.
//
// Pulls real company news from the Finnhub `/company-news` API for every company
// we track and stores it in `news_articles`, tagging each article to the ticker
// it belongs to via `article_stock_impacts`.
//
// WHY FINNHUB (replacing the earlier GDELT source):
// * Finnhub is queried BY TICKER (symbol=AAPL), so each article is already tied
//   to the exact company. No fuzzy phrase-matching, so we never mis-tag the
//   fruit "apple" or a "visa" travel story to a stock.
// * It is reachable from Vercel's servers (GDELT is IPv4-only and silently drops
//   cloud-provider IPs, which is why the old source always timed out).
// * The free tier allows 60 requests/minute, which is plenty for paging through
//   our company list a few at a time.
//
// HONESTY / SCOPE NOTES:
// * We store ONLY what Finnhub actually returns: headline, source name, url,
//   publish date, and the publisher's OWN summary (Finnhub's `summary` field is
//   written by the news outlet, not generated by us). We do NOT invent
//   sentiment, impact scores, or any up/down forecast. Those columns stay NULL.
// * We space our per-company requests out and process a small batch per call,
//   returning next_offset/done so a caller can page through the whole universe
//   (mirrors the /api/edgar-import pattern).

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export const maxDuration = 60

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

const FINNHUB_BASE = 'https://finnhub.io/api/v1/company-news'

// Finnhub free tier allows 60 requests/minute (= 1 per second). A 1.2s gap
// between company requests keeps us comfortably under that limit.
const REQUEST_GAP_MS = 1200
const FETCH_TIMEOUT_MS = 15000

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// undici's top-level Error is a useless "fetch failed" — the real reason (DNS,
// connection reset, TLS, blocked IP) lives on err.cause. Unwrap it so callers
// can actually see WHY a request failed instead of guessing.
function describeError(err) {
  const c = err && err.cause ? err.cause : null
  return {
    name: err?.name || null,
    message: err?.message || String(err),
    causeCode: c?.code || null,
    causeMessage: c?.message || null,
    causeErrno: c?.errno ?? null,
    causeSyscall: c?.syscall || null,
  }
}

// Format a Date as the YYYY-MM-DD string Finnhub expects for its from/to range.
function toDateStr(date) {
  return date.toISOString().slice(0, 10)
}

// Finnhub `datetime` is a Unix timestamp in SECONDS. Convert to an ISO string,
// guarding against missing/zero values.
function unixSecondsToIso(seconds) {
  if (!seconds || typeof seconds !== 'number') return null
  const ms = seconds * 1000
  const d = new Date(ms)
  return Number.isNaN(d.getTime()) ? null : d.toISOString()
}

// Build the Finnhub request URL. Kept private to this module so the token is
// never accidentally logged; use redactToken() before returning any URL.
function finnhubUrl(symbol, fromStr, toStr, token) {
  return (
    FINNHUB_BASE +
    '?symbol=' + encodeURIComponent(symbol) +
    '&from=' + encodeURIComponent(fromStr) +
    '&to=' + encodeURIComponent(toStr) +
    '&token=' + encodeURIComponent(token)
  )
}

// Replace the API token in any URL with the literal "REDACTED" so we can safely
// return the URL in a diagnostic response without leaking the key.
function redactToken(url) {
  return String(url || '').replace(/([?&]token=)[^&]*/i, '$1REDACTED')
}

// Single instrumented request. NEVER throws — it returns a structured result
// describing exactly what happened (transport error, HTTP status, or raw body)
// so failures are diagnosable instead of a bare "fetch failed".
async function rawFetch(url, timeoutMs = FETCH_TIMEOUT_MS) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(url, {
      headers: { Accept: 'application/json' },
      redirect: 'follow',
      signal: controller.signal,
    })
    const text = await res.text()
    const trimmed = (text || '').trim()
    // A successful company-news response is a JSON ARRAY, so it starts with "[".
    const looksJson = trimmed[0] === '[' || trimmed[0] === '{'
    return {
      transportOk: true,
      status: res.status,
      statusText: res.statusText,
      contentType: res.headers.get('content-type'),
      bodyLength: text.length,
      bodySnippet: trimmed.slice(0, 300),
      looksJson,
      rawText: text,
    }
  } catch (err) {
    return { transportOk: false, error: describeError(err) }
  } finally {
    clearTimeout(timer)
  }
}

// Fetch + parse company news for one ticker. Returns { articles, notice, diag }.
// Retries once on a transport-level failure, matching the old resilience.
async function fetchFinnhubNews(symbol, fromStr, toStr, token) {
  const url = finnhubUrl(symbol, fromStr, toStr, token)
  let r = await rawFetch(url)
  if (!r.transportOk) {
    await sleep(1500)
    r = await rawFetch(url)
  }
  if (!r.transportOk) {
    return { articles: [], notice: 'transport error', diag: r.error }
  }
  if (r.status !== 200) {
    // e.g. 429 (rate limit) or 401 (bad key). Redact just in case.
    return {
      articles: [],
      notice: `HTTP ${r.status}`,
      diag: { status: r.status, body: redactToken(r.bodySnippet) },
    }
  }
  try {
    const json = JSON.parse(r.rawText)
    // Finnhub returns an array on success, or an object like {"error":"..."} on
    // an access/quota problem served with a 200 status.
    if (Array.isArray(json)) return { articles: json }
    return { articles: [], notice: json?.error ? String(json.error) : 'unexpected Finnhub response' }
  } catch {
    return { articles: [], notice: 'unparseable Finnhub response', diag: { body: redactToken(r.bodySnippet) } }
  }
}

export async function GET(request) {
  try {
    const token = process.env.FINNHUB_API_KEY
    if (!token) {
      // Never pretend to work without the key — say so plainly.
      return NextResponse.json({ error: 'FINNHUB_API_KEY is not set' }, { status: 500 })
    }

    const url = new URL(request.url)
    const offset = parseInt(url.searchParams.get('offset') || '0', 10)
    const limit = parseInt(url.searchParams.get('limit') || '5', 10)
    // How many articles (at most) to keep per company, to avoid huge inserts for
    // heavily-covered tickers.
    const maxPerCompany = parseInt(url.searchParams.get('maxrecords') || '25', 10)
    // How many days back to pull news for, e.g. "3d" -> 3 days.
    const timespan = url.searchParams.get('timespan') || '3d'
    const days = Math.max(1, parseInt(timespan, 10) || 3)

    const toStr = toDateStr(new Date())
    const fromStr = toDateStr(new Date(Date.now() - days * 24 * 60 * 60 * 1000))

    // --- DIAGNOSTIC PROBE ------------------------------------------------
    // /api/ingest-news?probe=1 makes ONE Finnhub request (no DB writes, no
    // retry) with a short 5s timeout and returns the result immediately, so it
    // always answers within Vercel's function limit. Answers the only question
    // that matters: is Finnhub reachable from Vercel, and does it return data?
    if (url.searchParams.get('probe')) {
      const probeUrl = finnhubUrl('AAPL', fromStr, toStr, token)
      const r = await rawFetch(probeUrl, 5000)
      let articleCount = null
      if (r.transportOk && r.status === 200) {
        try {
          const json = JSON.parse(r.rawText)
          articleCount = Array.isArray(json) ? json.length : null
        } catch {
          articleCount = null
        }
      }
      return NextResponse.json({
        probe: true,
        source: 'Finnhub company-news',
        url: redactToken(probeUrl),
        transportOk: r.transportOk,
        status: r.status ?? null,
        articleCount,
        errorCode: r.error?.causeCode ?? r.error?.name ?? null,
        errorMessage: r.error?.causeMessage ?? r.error?.message ?? null,
        bodySnippet: r.bodySnippet ? redactToken(r.bodySnippet) : null,
      })
    }

    const { data: companies, error: cErr } = await supabase
      .from('companies')
      .select('id, ticker, name')
      .order('ticker')
    if (cErr) return NextResponse.json({ error: cErr.message }, { status: 500 })
    if (!companies || !companies.length) {
      return NextResponse.json({ error: 'No companies' }, { status: 400 })
    }

    const slice = companies.slice(offset, offset + limit)

    let articlesUpserted = 0
    let tagsUpserted = 0
    const results = []

    for (let i = 0; i < slice.length; i++) {
      const company = slice[i]
      const symbol = String(company.ticker || '').trim().toUpperCase()
      if (!symbol) {
        results.push({ ticker: company.ticker, skipped: 'no ticker' })
        continue
      }

      // Space out requests to respect Finnhub's rate limit (no sleep before the
      // very first request of this batch).
      if (i > 0) await sleep(REQUEST_GAP_MS)

      const news = await fetchFinnhubNews(symbol, fromStr, toStr, token)
      if (news.notice) {
        results.push({
          ticker: symbol,
          finnhubNotice: news.notice,
          diag: news.diag || undefined,
          articles: 0,
        })
        continue
      }

      // Build article rows, de-duped by url (Finnhub can repeat urls, and a
      // single insert cannot touch the same url twice).
      const byUrl = new Map()
      for (const a of news.articles) {
        const link = a.url
        const headline = a.headline
        if (!link || !headline) continue
        if (byUrl.has(link)) continue
        const cleanHeadline = String(headline).trim()
        // Store the publisher's own summary when it is present and adds
        // information beyond the headline. This is the outlet's text, not
        // anything we generated.
        const rawSummary = typeof a.summary === 'string' ? a.summary.trim() : ''
        const summary = rawSummary && rawSummary !== cleanHeadline ? rawSummary : null
        byUrl.set(link, {
          headline: cleanHeadline,
          url: link,
          source: a.source || null, // publication name, e.g. "Reuters"
          published_at: unixSecondsToIso(a.datetime),
          summary,
          // Deliberately NULL: category, impact, insider_signal, insider_note —
          // we do not fabricate any of these.
        })
        if (byUrl.size >= maxPerCompany) break
      }

      const rows = [...byUrl.values()]
      if (!rows.length) {
        results.push({ ticker: symbol, articles: 0 })
        continue
      }

      // Idempotent without depending on a DB-side unique constraint: look up
      // which urls we already have, insert only the new ones, then reuse the
      // ids for tagging. Re-running never duplicates an article.
      const urls = rows.map((r) => r.url)
      const idByUrl = new Map()
      const { data: existing, error: exErr } = await supabase
        .from('news_articles')
        .select('id, url')
        .in('url', urls)
      if (exErr) {
        results.push({ ticker: symbol, error: exErr.message })
        continue
      }
      for (const row of existing || []) idByUrl.set(row.url, row.id)

      const toInsert = rows.filter((r) => !idByUrl.has(r.url))
      if (toInsert.length) {
        const { data: inserted, error: aErr } = await supabase
          .from('news_articles')
          .insert(toInsert)
          .select('id, url')
        if (aErr) {
          results.push({ ticker: symbol, error: aErr.message })
          continue
        }
        for (const row of inserted || []) idByUrl.set(row.url, row.id)
        articlesUpserted += (inserted || []).length
      }

      // Tag every stored article to this company's ticker.
      const impacts = rows
        .map((r) => idByUrl.get(r.url))
        .filter(Boolean)
        .map((articleId) => ({
          article_id: articleId,
          company_id: company.id,
          ticker: symbol,
        }))
      const { error: iErr, count } = await supabase
        .from('article_stock_impacts')
        .upsert(impacts, { onConflict: 'article_id,ticker', count: 'exact' })
      if (iErr) {
        results.push({ ticker: symbol, articles: rows.length, tagError: iErr.message })
        continue
      }
      tagsUpserted += (count ?? impacts.length)
      results.push({ ticker: symbol, articles: rows.length })
    }

    const nextOffset = offset + limit
    return NextResponse.json({
      success: true,
      source: 'Finnhub company-news',
      processed: slice.map((c) => c.ticker),
      articles_upserted: articlesUpserted,
      tags_upserted: tagsUpserted,
      results,
      next_offset: nextOffset,
      done: nextOffset >= companies.length,
      total_companies: companies.length,
    })
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
